credentials:
  usernames:
    user1:
      email: user1@example.com
      name: Mick Jagger 
      password: "123"
    user2:
      email: user2@example.com
      name: Freddie Mercury 
      password: "123"
    user3:
      email: user3@example.com
      name: Robert Plant
      password: "123"

cookie:
  expiry_days: 1
  key: my_super_secret_key_123
  name: user_session

preauthorized:
  emails:
    - user1@example.com
    - user2@example.com
